# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b5f49862337bdd809336592463979800b7b3cd6a519f35a4b722b7e115720424c624df3615d2210b3db7b2bc008f44785013e69f5ccde15b5b9741ac58e3ade

test:
  secret_key_base: ea1ff6b9598444d1fe8ee510a39fb3411e8a0cb7de4cc0fde6998d1e72d4104789a9b16b08d9f080d31d8f448bb9b836191e1a6a8d04c103f7742fcd47f66ad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
